name: C++ backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Newer commits should cancel old runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up NEML2 environment
        uses: applied-material-modeling/neml2-ci@main
        with:
          path: neml2-src
          python-version: 3.9
          cmake-version: 3.26
          torch-version: 2.5.1
      - name: Install NEML2
        run: |
          cmake --preset runner -GNinja -S neml2-src -B neml2-build
          cmake --build neml2-build
          cmake --install neml2-build --prefix neml2-install
      - name: Build custom library
        run: |
          cmake -Dneml2_ROOT=neml2-install -B build
          cmake --build build
      - name: Run tests
        run: neml2-install/bin/runner inspect test.i model
